### ISSUE TITLE
Multiple drops and drop chances per mob.

### ISSUE THREAD

**Issue by Maddude174** [AlonsoAliaga/BetterEconomy#1]
NOTICE THAT THIS IS JUST A REQUEST. FEATURE CAN NEVER BE ADDED.

**Is your feature request related to a problem? Please describe.**
more or less; with the drops system as it is you can only define one value and a drop chance once per mob.
i'm trying to add a loot table to mobs to randomize the reward given.

**Describe the solution you'd like**
  CREEPER:
    normal:
      Requires-killer: true
      Money: "option 1"
      Chance: 30
      Money: "option 2"
      Chance: 30
      Money: "option 3"
      Chance: 30

**Describe alternatives you've considered**
ive tried the above solution aswell as defining each option multiple times like so;
  CREEPER:
    normal:
      Requires-killer: true
      Money: "option 1"
      Chance: 30
  CREEPER:
    normal:
      Requires-killer: true
      Money: "option 2"
      Chance: 30

**Additional context**
currently; both above options break the config and disable drops for that mob.

**Comment by AlonsoAliaga** [comment]
Hello, this is impossible. Seems easy to implement, I know, but it's complex, maths to make such as system is not that easy to implement. I'll consider it, but it won't be implemented soon

**Comment by AlonsoAliaga** [comment]
Cannot be implemented due to complex systems
