### ISSUE TITLE
How to use Metadata?

### ISSUE THREAD

**Issue by t0ngk** [AlonsoAliaga/BetterEconomy#2]
First Sorry for my English am not really good at it

I just want to know how to use Metadata because I want to use this plugin with mythic mobs
but I don't know how to add Metadata to my mob
please can you tell me how to use or apply to mythic mobs

thank you sorry for my English again

**Comment by AlonsoAliaga** [comment]
Hello, this plugin doesn't hook with any plugin, it only allows metadata to "select" the entity.
You can choose 1) entity type and metadata or simply metadata.
You can only specify the metadata in BetterEconomy, but related to the other plugin, it must be added by the other plugin.
Make sure MythicMobs adds an specific metadata to the mobs (you can also ask the developer of that plugin, in his discord server)
If you have more questions, join my discord server so we can talk easier and I can reply faster on https://alonsoaliaga.com/discord
